/**
 * build.mjs — stages ds-bundle/ for upload to Claude Design.
 *
 * This repo is a Claude Design EXPORT, not a source component library: there is
 * no dist/, no Storybook, and _ds_manifest.json declares zero components. So
 * the usual /design-sync converter does not apply. What this script does is fix
 * the four things that stop the exported package from being uploaded as-is:
 *
 *   1. Adds a styles.css entry that @imports colors_and_type.css. Rendered
 *      designs only receive styles.css's transitive @import closure, so the
 *      tokens have to be reachable from it.
 *   2. Replaces the stale "HelmMobileUIKitDesignSystem_82e1d8" namespace (a
 *      leftover from the kit this was remixed from) with an Interflora one.
 *   3. Makes the two UI kit cards self-contained: React/ReactDOM are vendored
 *      from node_modules and the kits load the already-compiled _ds_bundle.js
 *      instead of compiling JSX in the browser with Babel standalone. Only each
 *      kit's inline App block still needs compiling, which esbuild does here.
 *   4. Swaps the seven remote avatars and six remote product photos for
 *      generated on-token SVG data URIs, so no card reaches an external host.
 *
 * It also regenerates _ds_manifest.json from colors_and_type.css and the
 * @dsCard markers, because the committed manifest records a --font-brand value
 * ('Sohne', 'Gotham', Arial, ...) that the CSS no longer has.
 */

import { readFile, writeFile, mkdir, rm, cp, readdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';
import * as esbuild from 'esbuild';

const ROOT = import.meta.dirname;
const OUT = path.join(ROOT, 'ds-bundle');

const NAMESPACE = 'InterfloraGroupDesignSystem_82e1d8';
const STALE_NAMESPACE = 'HelmMobileUIKitDesignSystem_82e1d8';
const CSS = 'colors_and_type.css';

const sha12 = (s) => createHash('sha256').update(s).digest('hex').slice(0, 12);
const read = (p) => readFile(path.join(ROOT, p), 'utf8');
const write = async (rel, data) => {
  const dest = path.join(OUT, rel);
  await mkdir(path.dirname(dest), { recursive: true });
  await writeFile(dest, data);
};

/* ------------------------------------------------------------------ avatars */
/* Background/glyph pairs follow the --on-* rules in colors_and_type.css:
   purple and the Flying Flowers headings take white, everything else black. */
const AVATAR_PAIRS = [
  ['#9B00FE', '#FFFFFF'], // if-purple      -> --on-purple
  ['#FF0050', '#000000'], // if-red         -> --on-red
  ['#04FF7E', '#000000'], // if-green       -> --on-green
  ['#FEDC00', '#000000'], // if-yellow      -> --on-yellow
  ['#FF842B', '#000000'], // if-orange      -> --on-orange
  ['#CAAD59', '#000000'], // if-gold        -> --on-gold
  ['#C366FF', '#000000'], // if-mid-purple  -> --on-mid-purple
  ['#007FA3', '#FFFFFF'], // ff-cobalt      -> FF always white
  ['#048670', '#FFFFFF'], // ff-jade        -> FF always white
  ['#E01761', '#FFFFFF'], // ff-wild-exotic -> FF always white
];

/* Bouquet placeholder palettes: a light brand tint behind a brand-coloured
   flower. Each triple is [background, petals, centre], all token values. */
const BOUQUET_PALETTES = [
  ['#E9CBFF', '#9B00FE', '#FEDC00'], // lilac / purple / yellow
  ['#FFCBDB', '#FF0050', '#FEDC00'], // pink / red / yellow
  ['#CBFFE4', '#04FF7E', '#FF842B'], // light-green / green / orange
  ['#FFF7CB', '#FEDC00', '#FF842B'], // light-yellow / yellow / orange
  ['#FECCA7', '#FF842B', '#9B00FE'], // peach / orange / purple
];

const PLACEHOLDER_JS = `/* Generated by build.mjs — deterministic, on-token image placeholders.
   The exported kits pointed at two third-party image services; these replace
   them so no design-system card depends on an external host. */
(function () {
  var NS = 'http://www.w3.org/2000/svg';
  var uri = function (svg) {
    return 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(svg);
  };

  var PAIRS = ${JSON.stringify(AVATAR_PAIRS)};
  window.IF_AVATAR = function (seed) {
    var n = Math.abs(parseInt(seed, 10) || 0);
    var pair = PAIRS[n % PAIRS.length];
    return uri('<svg xmlns="' + NS + '" viewBox="0 0 80 80">' +
      '<rect width="80" height="80" fill="' + pair[0] + '"/>' +
      '<circle cx="40" cy="32" r="13" fill="' + pair[1] + '"/>' +
      '<path d="M13 80c0-14.9 12.1-27 27-27s27 12.1 27 27z" fill="' + pair[1] + '"/></svg>');
  };

  var PALETTES = ${JSON.stringify(BOUQUET_PALETTES)};
  window.IF_BOUQUET = function (seed, w, h) {
    w = w || 400; h = h || 300;
    var key = String(seed), sum = 0;
    for (var i = 0; i < key.length; i++) sum = (sum * 31 + key.charCodeAt(i)) % 9973;
    var p = PALETTES[sum % PALETTES.length];
    var cx = w / 2, cy = h / 2, r = Math.min(w, h) * 0.26;
    var petals = '';
    for (var a = 0; a < 6; a++) {
      petals += '<ellipse cx="' + cx + '" cy="' + (cy - r * 0.62) + '" rx="' + (r * 0.34) +
        '" ry="' + (r * 0.62) + '" fill="' + p[1] + '" transform="rotate(' +
        (a * 60) + ' ' + cx + ' ' + cy + ')"/>';
    }
    return uri('<svg xmlns="' + NS + '" viewBox="0 0 ' + w + ' ' + h + '">' +
      '<rect width="' + w + '" height="' + h + '" fill="' + p[0] + '"/>' +
      '<path d="M' + cx + ' ' + cy + ' L' + cx + ' ' + (cy + r * 1.5) +
      '" stroke="#04FF7E" stroke-width="' + Math.max(2, r * 0.1) + '" fill="none"/>' +
      petals + '<circle cx="' + cx + '" cy="' + cy + '" r="' + (r * 0.3) +
      '" fill="' + p[2] + '"/></svg>');
  };
})();
`;

/**
 * Rewrite both remote image services to local generators. Covers the markup
 * spelling and the compiled-JS spelling, and both the plain-string and
 * template-literal forms.
 */
function localiseImages(src) {
  const before = src;
  const out = src
    // `https://i.pravatar.cc/80?img=${p.img}`   ->  IF_AVATAR(p.img)
    .replace(/`https:\/\/i\.pravatar\.cc\/\d+\?img=\$\{([^}]*)\}`/g, 'IF_AVATAR($1)')
    // 'https://i.pravatar.cc/120?img=47'        ->  IF_AVATAR(47)
    .replace(/(['"])https:\/\/i\.pravatar\.cc\/\d+\?img=(\d+)\1/g, 'IF_AVATAR($2)')
    // 'https://picsum.photos/seed/flowers1/400/300' -> IF_BOUQUET('flowers1',400,300)
    .replace(
      /(['"])https:\/\/picsum\.photos\/seed\/([^/'"]+)\/(\d+)\/(\d+)\1/g,
      "IF_BOUQUET('$2',$3,$4)",
    )
    // `https://picsum.photos/seed/${x}/400/300`  -> IF_BOUQUET(x,400,300)
    .replace(
      /`https:\/\/picsum\.photos\/seed\/\$\{([^}]*)\}\/(\d+)\/(\d+)`/g,
      'IF_BOUQUET($1,$2,$3)',
    );
  return { out, changed: before !== out };
}

/* ------------------------------------------------------------------- tokens */
function classifyToken(name, value) {
  if (name.startsWith('--font-')) return 'font';
  if (name.startsWith('--e-')) return 'shadow';
  if (name.startsWith('--s-') || name.startsWith('--r-')) return 'spacing';
  if (name.startsWith('--fw-') || name.startsWith('--ease-') || name.startsWith('--dur-')) return 'other';
  if (/^(#|rgb|hsl)/i.test(value) || /^var\(--/.test(value)) return 'color';
  return 'other';
}

/** Every custom property declared in the stylesheet, in source order. */
function parseTokens(css) {
  const stripped = css.replace(/\/\*[\s\S]*?\*\//g, '');
  const tokens = [];
  const seen = new Set();
  for (const m of stripped.matchAll(/(--[a-z0-9-]+)\s*:\s*([^;}]+)/gi)) {
    const name = m[1];
    const value = m[2].trim();
    // .brand-ff redeclares :root names; keep the first (default Interflora)
    // definition, matching how the exported manifest counted them.
    const key = `${name}::${value}`;
    if (seen.has(key)) continue;
    seen.add(key);
    tokens.push({ name, value, kind: classifyToken(name, value), definedIn: CSS });
  }
  return tokens;
}

/* -------------------------------------------------------------------- cards */
/** Read the @dsCard marker the app compiles its card index from. */
function parseCard(html, relPath) {
  const m = html.match(/<!--\s*@dsCard\s+([^>]*?)-->/);
  if (!m) return null;
  const attrs = {};
  for (const a of m[1].matchAll(/(\w+)="([^"]*)"/g)) attrs[a[1]] = a[2];
  const card = { path: relPath, group: attrs.group || 'Components' };
  if (attrs.name) card.name = attrs.name;
  if (attrs.subtitle) card.subtitle = attrs.subtitle;
  if (attrs.viewport) {
    const [w, h] = attrs.viewport.split('x').map(Number);
    if (w) card.viewport = h ? { width: w, height: h } : { width: w };
  }
  return card;
}

/* --------------------------------------------------------------------- kits */
const KITS = ['business-crm', 'interflora-shop'];

/**
 * Rewrite a kit's index.html: drop the three CDN <script> tags and the
 * per-file text/babel tags, load vendored React plus the compiled bundle, and
 * inline the kit's own App block compiled from JSX to plain JS.
 */
async function buildKit(kit) {
  const rel = `ui_kits/${kit}/index.html`;
  const html = await read(rel);

  const card = parseCard(html, rel);
  if (!card) throw new Error(`${rel}: no @dsCard marker`);

  // The kit's App lives in the last inline text/babel block.
  const inline = [...html.matchAll(/<script type="text\/babel">([\s\S]*?)<\/script>/g)];
  if (inline.length !== 1) throw new Error(`${rel}: expected 1 inline babel block, found ${inline.length}`);

  const { out: appSrc } = localiseImages(inline[0][1]);
  const { code: appJs } = await esbuild.transform(appSrc, {
    loader: 'jsx',
    jsx: 'transform',
    target: 'es2018',
    format: undefined,
  });

  const head = html.slice(0, html.indexOf('<script'));
  const localStyle = (html.match(/<style>[\s\S]*?<\/style>/) || [''])[0];
  const title = (html.match(/<title>([^<]*)<\/title>/) || [, kit])[1];
  const marker = (html.match(/<!--\s*@dsCard[^>]*-->/) || [''])[0];

  const rebuilt = `<!DOCTYPE html>
${marker}
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${title}</title>
<link rel="stylesheet" href="../../${CSS}">
<script src="../../_vendor/react.production.min.js"></script>
<script src="../../_vendor/react-dom.production.min.js"></script>
<script src="../../_vendor/ds-placeholders.js"></script>
<script src="../../_ds_bundle.js"></script>
${localStyle}
</head>
<body>
<div id="root"></div>
<script>
${appJs.trim()}
</script>
</body>
</html>
`;
  await write(rel, rebuilt);
  void head;
  return card;
}

/* --------------------------------------------------------------------- main */
async function main() {
  await rm(OUT, { recursive: true, force: true });
  await mkdir(OUT, { recursive: true });

  // 1. Stylesheet plus the styles.css entry designs actually receive.
  const css = await read(CSS);
  await write(CSS, css);
  await write(
    'styles.css',
    `/* Entry point for rendered designs.
   Claude Design gives a design only this file's transitive @import closure,
   so every Interflora token has to be reachable from here. */
@import url("./${CSS}");
`,
  );

  // 2. Spec cards, copied verbatim — they are plain HTML/CSS with no scripts.
  const cards = [];
  const previews = (await readdir(path.join(ROOT, 'preview'))).filter((f) => f.endsWith('.html')).sort();
  for (const f of previews) {
    const rel = `preview/${f}`;
    const html = await read(rel);
    if (/<script/i.test(html)) throw new Error(`${rel}: unexpected <script>; spec cards must stay static`);
    const card = parseCard(html, rel);
    if (!card) throw new Error(`${rel}: no @dsCard marker`);
    cards.push(card);
    await write(rel, html);
  }

  // 3. Vendored React, so the kits need no CDN and no Babel standalone.
  await write('_vendor/ds-placeholders.js', PLACEHOLDER_JS);
  for (const [pkg, file] of [
    ['react', 'react.production.min.js'],
    ['react-dom', 'react-dom.production.min.js'],
  ]) {
    await cp(path.join(ROOT, 'node_modules', pkg, 'umd', file), path.join(OUT, '_vendor', file));
  }

  // 4. The compiled bundle: namespace corrected, avatars de-externalised.
  let bundle = await read('_ds_bundle.js');
  if (!bundle.includes(STALE_NAMESPACE)) throw new Error('_ds_bundle.js: stale namespace not found — did the export change?');
  bundle = bundle.replaceAll(STALE_NAMESPACE, NAMESPACE);
  const localised = localiseImages(bundle);
  if (!localised.changed) throw new Error('_ds_bundle.js: expected remote image URLs to rewrite, none matched');
  bundle = localised.out;
  for (const host of ['i.pravatar.cc', 'picsum.photos']) {
    if (bundle.includes(host)) throw new Error(`_ds_bundle.js: ${host} survived the rewrite`);
  }
  await write('_ds_bundle.js', bundle);

  // 5. UI kit cards, plus the kit JSX as readable usage examples. This design
  //    system declares no components, so these files are the only real
  //    Interflora-styled React the design agent can learn the idiom from.
  //    Their remote image URLs are localised too, so nothing here teaches the
  //    agent to fetch from a third-party host.
  for (const kit of KITS) cards.push(await buildKit(kit));

  const examples = ['ui_kits/icons.jsx'];
  for (const kit of KITS) {
    for (const f of await readdir(path.join(ROOT, 'ui_kits', kit))) {
      if (f.endsWith('.jsx') || f === 'README.md') examples.push(`ui_kits/${kit}/${f}`);
    }
  }
  for (const rel of examples) {
    const src = await read(rel);
    await write(rel, rel.endsWith('.jsx') ? localiseImages(src).out : src);
  }

  // 6. Manifest, regenerated from the CSS and the @dsCard markers.
  const tokens = parseTokens(css);
  const manifest = {
    namespace: NAMESPACE,
    components: [],
    startingPoints: [],
    cards: cards.sort((a, b) => a.group.localeCompare(b.group) || a.path.localeCompare(b.path)),
    templates: [],
    globalCssPaths: ['styles.css', CSS],
    tokens,
    themes: [{ selector: '.brand-ff', label: 'Flying Flowers' }],
    fonts: [],
    // Arial is the digital brand face: a system font, so there is nothing to
    // load. Soehne stays the print typeface and is deliberately not on screen.
    brandFonts: [],
    source: 'spa',
  };
  await write('_ds_manifest.json', JSON.stringify(manifest, null, 2) + '\n');

  // 7. README with the hand-authored conventions header prepended.
  const body = await read('README.md');
  let readme = body;
  try {
    const header = await read('.design-sync/conventions.md');
    readme = `${header.trim()}\n\n---\n\n${body}`;
  } catch {
    console.warn('! .design-sync/conventions.md missing — README has no conventions header');
  }
  await write('README.md', readme);

  // 8. Lint rules that keep generated output on-token.
  await write('_adherence.oxlintrc.json', await read('_adherence.oxlintrc.json'));

  // 9. Sync anchor. shape:"export" is specific to this repo, so a future
  //    /design-sync run that does not recognise it will re-verify everything,
  //    which is the correct fallback.
  const files = [];
  const walk = async (dir) => {
    for (const e of await readdir(path.join(OUT, dir), { withFileTypes: true })) {
      const rel = dir ? `${dir}/${e.name}` : e.name;
      if (e.isDirectory()) await walk(rel);
      else files.push(rel);
    }
  };
  await walk('');
  const sourceHashes = {};
  for (const f of files.sort()) {
    if (f === '_ds_sync.json') continue;
    sourceHashes[f] = sha12(await readFile(path.join(OUT, f)));
  }
  await write(
    '_ds_sync.json',
    JSON.stringify(
      {
        shape: 'export',
        keyRecipe: 'sha256(file bytes) truncated to 12 hex chars, per uploaded path',
        namespace: NAMESPACE,
        styleSha: sha12(css),
        bundleSha12: sha12(bundle),
        renderHashes: {},
        sourceHashes,
        builtBy: 'build.mjs',
      },
      null,
      2,
    ) + '\n',
  );

  const counts = tokens.reduce((a, t) => ((a[t.kind] = (a[t.kind] || 0) + 1), a), {});
  console.log(`ds-bundle/ built: ${files.length} files`);
  console.log(`  cards:  ${cards.length}`);
  console.log(`  tokens: ${tokens.length} ${JSON.stringify(counts)}`);
}

await main();
